const constants = {
  PERSISTENT_DATA_DIR: 'PERSISTENT_DATA_DIR',
  MYSQL_DB_HOST: 'MYSQL_DB_HOST',
  MYSQL_DB_USERNAME: 'MYSQL_DB_USERNAME',
  MYSQL_DB_PASSWORD: 'MYSQL_DB_PASSWORD',
  MYSQL_DB_NAME: 'MYSQL_DB_NAME'
}

exports = constants